---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-hotrod-svc
  namespace: spp-ns
  labels:
    app: jaeger-hotrod-svc
    application.owner: spp.com
    version: v1
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30090
    
  selector:
    app: jaeger-hotrod-deploy
    application.owner: spp.com
    version: v1